# Generated by Django 4.2.13 on 2024-06-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="profiles",
        ),
    ]
