# Generated by Django 4.2.13 on 2024-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follows",
            field=models.ManyToManyField(
                related_name="followed_by", to="accounts.profile"
            ),
        ),
    ]
