# Generated by Django 4.2.13 on 2024-06-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_remove_workout_user_workout_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout",
            options={"ordering": ["-date"]},
        ),
    ]
