# Generated by Django 4.2.13 on 2024-06-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_workout_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "workout_exercises",
            },
        ),
    ]
