# Generated by Django 4.2.13 on 2024-06-27 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
        ("workouts", "0005_workoutexercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercises.exercise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="workout",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="workouts.workout",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("lb", "lb")], default="lb", max_length=2
                    ),
                ),
                (
                    "repetitions",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("seconds", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.workoutexercise",
                    ),
                ),
            ],
            options={
                "db_table": "sets",
            },
        ),
    ]
