# Generated by Django 4.2.13 on 2024-06-29 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_workoutexercise_exercise_workoutexercise_workout_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout",
            options={"ordering": ["-date", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="set",
            name="weight_unit",
            field=models.CharField(
                choices=[("kg", "kgs"), ("lb", "lbs")], default="lb", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="set",
            name="workout_exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="workouts.workoutexercise",
            ),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="workouts.workout",
            ),
        ),
    ]
